In [1]:
%matplotlib inline
import time
import math
from keras.models import load_model
from keras.preprocessing import image
import cv2
import numpy as np
import signal
import sys
import matplotlib.pyplot as plt
from Bebop import Bebop
from DroneVision import DroneVision
from preprocess import preprocess

Using TensorFlow backend.
/Users/alexchan/anaconda3/envs/MLKart/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
def rightArc():
#     #rotate in an arc to the right
#     bebop.fly_direct(roll=15, pitch=0, yaw=0, vertical_movement=0, duration=3)
#     bebop.fly_direct(roll=0, pitch=15, yaw=0, vertical_movement=0, duration=3)
#     bebop.fly_direct(roll=0, pitch=0, yaw=20, vertical_movement=0, duration=4)
    print('right')
    return

def leftArc():
#     bebop.fly_direct(roll=-15, pitch=0, yaw=0, vertical_movement=0, duration=3)
#     bebop.fly_direct(roll=0, pitch=-15, yaw=0, vertical_movement=0, duration=3)
#     bebop.fly_direct(roll=0, pitch=0, yaw=-5, vertical_movement=0, duration=4)
    print('left')
    return

def land():
    active = False
    print('land')
    return

def flip():
#     bebop.flip(back)
    print('flip')
    return

def resolveAction(gesture):
    actions = {
        0 : rightArc,
        1 : leftArc,
        2 : land,
        3 : flip # TODO: Replace this with do nothing command?
    }
    actions[gesture]
    return

def kill(signal, frame):
    """ Catches SIGINT and lands the drone """

    print("Ctrl+C registed - exiting gracefully")
    bebop.smart_sleep(5)
    bebop.safe_land(10)
    print("Landed successfully. Now exiting")
    bebop.disconnect()
    sys.exit(0)

signal.signal(signal.SIGINT, kill)


<function _signal.default_int_handler>

In [3]:
class UserVision:
    def __init__(self, vision):
        self.index = 0
        self.vision = vision

    def save_pictures(self, args):
        #print("saving picture")
        img = self.vision.get_latest_valid_picture()

        # filename = "test_image_%06d.png" % self.index
        #cv2.imwrite(filename, img)
        self.index +=1

    def detect(self, args):
        img = self.vision.get_latest_valid_picture()


In [4]:
model = load_model('4_gesture_model.h5')

In [11]:
bebop = Bebop()


timeout - trying again
timeout - trying again
Service Bebop2-C409587._arsdk-090c._udp.local. added, service info: ServiceInfo(type='_arsdk-090c._udp.local.', name='Bebop2-C409587._arsdk-090c._udp.local.', address=b'\xc0\xa8*\x01', port=44444, weight=0, priority=0, server='Bebop2-C409587.local.', properties={b'{"device_id":"PI040376AA6C409587"}': False})


In [10]:
success = bebop.connect(5)

active = True
COUNT_EVERY = 20

if (success):
    # start up the video
    bebopVision = DroneVision(bebop, is_bebop=True)

    # Load model
    model = load_model('4_gesture_model.h5')

    userVision = UserVision(bebopVision)
    bebopVision.set_user_callback_function(userVision.save_pictures, user_callback_args=None)
    success = bebopVision.open_video()
    print(success)
    

Service Bebop2-C409587._arsdk-090c._udp.local. added, service info: ServiceInfo(type='_arsdk-090c._udp.local.', name='Bebop2-C409587._arsdk-090c._udp.local.', address=b'\xc0\xa8*\x01', port=44444, weight=0, priority=0, server='Bebop2-C409587.local.', properties={b'{"device_id":"PI040376AA6C409587"}': False})
{"d2c_port": 43210, "controller_type": "computer", "controller_name": "pyparrot", "arstream2_client_stream_port": 55004, "arstream2_client_control_port": 55005}
{'status': 0, 'c2d_port': 54321, 'c2d_update_port': 51, 'c2d_user_port': 21, 'qos_mode': 0, 'arstream2_server_stream_port': 5004, 'arstream2_server_control_port': 5005}
c2d_port is 54321


OSError: [Errno 48] Address already in use

timeout - trying again
timeout - trying again
timeout - trying again
timeout - trying again
timeout - trying again
timeout - trying again


In [6]:
bebopVision = DroneVision(bebop, is_bebop=True)

# Load model

userVision = UserVision(bebopVision)
bebopVision.set_user_callback_function(userVision.save_pictures, user_callback_args=None)
success = bebopVision.open_video()

54
/Users/alexchan/Documents/college/uavs/flywave/flywave/images
/Users/alexchan/Documents/college/uavs/flywave/flywave/utils
Opening ffmpeg
ffmpeg -protocol_whitelist "file,rtp,udp" -i /Users/alexchan/Documents/college/uavs/flywave/flywave/utils/bebop.sdp -r 30 image_%03d.png &
starting vision thread
Opening non-blocking readers
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers

  built with Apple LLVM version 8.1.0 (clang-802.0.42)

  configuration: 

  libavutil      55. 58.100 / 55. 58.100

  libavcodec     57. 89.100 / 57. 89.100

  libavformat    57. 71.100 / 57. 71.100

  libavdevice    57.  6.100 / 57.  6.100

  libavfilter     6. 82.100 /  6. 82.100

  libswscale      4.  6.100 /  4.  6.100

  libswresample   2.  7.100 /  2.  7.100

[udp @ 0x7fe8af2000c0] bind failed: Address already in use

/Users/alexchan/Documents/college/uavs/flywave/flywave/utils/bebop.sdp: Invalid data found when processing input



KeyboardInterrupt: 

In [37]:


print("Vision successfully started!")
#removed the user call to this function (it now happens in open_video())
#bebopVision.start_video_buffering()

# skipping actually flying for safety purposes indoors - if you want
# different pictures, move the bebop around by hand
print("Fly me around by hand!")
bebop.smart_sleep(5)
print("Moving the camera using velocity")
# bebop.pan_tilt_camera_velocity(pan_velocity=0, tilt_velocity=-2, duration=4)

bebop.safe_takeoff(10)
bebop.fly_direct(roll=0, pitch=0, yaw=0, vertical_movement=20, duration=1)
bebop.smart_sleep(5)

count = 0
scale = 4

while active:
    if count % COUNT_EVERY == 0:
        #TODO: How to get individual frames from video stream in bebop?
        img = userVision.vision.get_latest_valid_picture()
#         cv2.imwrite('curr_frame.png', img)
#         img = image.load_img('curr_frame.png', grayscale=True)
        img = image.img_to_array(img)
        print(img.shape)
#         plt.imshow(img)
#         img = preprocess(img, 4)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        blur = cv2.GaussianBlur(img,(5,5),0)
#         ret, img = cv2.threshold(blur,70,255,cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)
        img = cv2.resize(img, (img.shape[1]//scale, img.shape[0]//scale))
        img = np.resize(img, (1, img.shape[0], img.shape[1],1))
        prediction = model.predict(img)
        print(prediction)
        if len(prediction) > 0:
            gesture = np.argmax(prediction[0])
            #print(gesture, prediction)
            resolveAction(gesture)
    count += 1
    if count == 2000:
        break

bebop.smart_sleep(5)
bebop.safe_land(10)
print("Done - Disconnecting")

bebop.disconnect()



Vision successfully started!
Fly me around by hand!
Moving the camera using velocity
roll is 0 pitch is 0 yaw is 0 vertical is 20
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1.  0.  0.  0.]]
(480, 856, 3)
[[ 1. 

KeyboardInterrupt: 

In [1]:
bebop.disconnect()


NameError: name 'bebop' is not defined